### ISSUE TITLE
Create view variable page

### ISSUE THREAD

**Issue by chokputtaraksa** [QAAFI/Apsim.Variables#2]
- Be able to filter variable name, also be able to filter the next gen name
- Display multiple column [can remove the description]

**Comment by chokputtaraksa** [comment]
View variable page will be imitated from edit page, but change the input fields to disabled.

My idea:
- should we let the user upload the variable to this page, let them edit and let them download? 


![image](https://user-images.githubusercontent.com/13741366/185726842-107cb302-4832-41cf-b82b-86ce15661e48.png)

**Comment by jbrider** [comment]
How will that work with multiple columns?
Being able to view more variables on screen was an important goal.

I will also add an issue about adding tags to be able to sort/filter on them as well.

**Comment by chokputtaraksa** [comment]
I will create something like dropdown list which show what the user can filter and then when they selected the filter, the typing something there and click search the word will be change to pill with some color that indicated what type it is related to. After that the user can still change the dropdown and input a new search string without effecting anything.

![image](https://user-images.githubusercontent.com/13741366/185839169-87d43240-98c1-4350-a50d-57cdaed1d175.png)
