### ISSUE TITLE
Adding Tags

### ISSUE THREAD

**Issue by jbrider** [QAAFI/Apsim.Variables#4]
Add functionality to be able to add tags to a variable.
The tags should be stored as space delimited strings.
As it will be space limited, tags cannot have spaces in them.
A variable can have multiple tags.
We will want to filter tags.
We may want to sort on tags, but only if it is quick and easy to implement (not a priority)

Examples include: Biomass, Nitrogen, Grain, Leaf.

**Comment by chokputtaraksa** [comment]
![image](https://user-images.githubusercontent.com/13741366/185790444-31a5af49-2bba-429f-931f-526348113902.png)


is [Sorghum] the tag that you want me to make it to be able to filter?
right now, it can only filter by variable name.

Sorry, I forget some part of the discussion that we talked on last Monday.

**Comment by jbrider** [comment]
No, that is part of the nextgen name - which we also want to be able to filter on.

Tags will be a new field to be able to edit.
