### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by jbrider** [QAAFI/Apsim.Variables#5]
Add some information on the readme describing how the github pages work.
Don't recreate the tutorial, add it as a link.
Just a summary of how the different parts are related.
Add a link to the actual page.

**Comment by jbrider** [comment]
There is a pull request that is asking to be merged into master that has a lot of production output?
They are supposed to be in the gh-pages - I don't think they need to be in the master branch as well do they?

**Comment by chokputtaraksa** [comment]
> There is a pull request that is asking to be merged into master that has a lot of production output? They are supposed to be in the gh-pages - I don't think they need to be in the master branch as well do they?

Yes, I get what you mean, however, if I want to ignore it I have to think of the way to handle how to publish ./out folder to gh-pages branch, which I am working on it right now.

**Comment by chokputtaraksa** [comment]
Ok, I get what you mean, I will fix it!
